### ISSUE TITLE
好奇问一句人脸识别(人脸分类)

### ISSUE THREAD

**Issue by cgpeter96** [CaptainEven/Face-recognition-#1]
这样理解对吗 = =  加了triplet loss 是为了更好的提取特征？

**Comment by CaptainEven** [comment]
triplet loss是为了更好的区分类内与类间特征差距，相当于聚类的思想，通过triplet loss训练一个特征提取网络，使得这个网络提取的特征尽量满足，同类特征比较接近，不同类特征距离比较远。
